/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlockchainBlockHeader: typeof import('./components/blockchain/block/Header.vue')['default']
    BlockchainBlockSectionHeader: typeof import('./components/blockchain/block/section/Header.vue')['default']
    BlockchainBlockSectionTable: typeof import('./components/blockchain/block/section/Table.vue')['default']
    BlockchainBlockSectionVotes: typeof import('./components/blockchain/block/section/Votes.vue')['default']
    BlockchainBlockTable: typeof import('./components/blockchain/block/Table.vue')['default']
    BlockchainBlockTransactionHeader: typeof import('./components/blockchain/block/transaction/Header.vue')['default']
    BlockchainBlockTrxHeader: typeof import('./components/blockchain/block/trx/Header.vue')['default']
    BlockchainBlockTrxOverview: typeof import('./components/blockchain/block/trx/Overview.vue')['default']
    BlockchainBlockVotes: typeof import('./components/blockchain/block/Votes.vue')['default']
    BlockchainHeader: typeof import('./components/blockchain/Header.vue')['default']
    BlockchainSectionHeader: typeof import('./components/blockchain/section/Header.vue')['default']
    BlockchainSectionTable: typeof import('./components/blockchain/section/Table.vue')['default']
    BlockchainSectionVotes: typeof import('./components/blockchain/section/Votes.vue')['default']
    BlockchainTable: typeof import('./components/blockchain/Table.vue')['default']
    BlockchainVotes: typeof import('./components/blockchain/Votes.vue')['default']
    Column: typeof import('primevue/column')['default']
    CoverWrapper: typeof import('./components/CoverWrapper.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    HomeCommunity: typeof import('./components/home/Community.vue')['default']
    HomeHeader: typeof import('./components/home/Header.vue')['default']
    HomeHighlight: typeof import('./components/home/Highlight.vue')['default']
    HomeSectionCommunity: typeof import('./components/home/section/Community.vue')['default']
    HomeSectionHeader: typeof import('./components/home/section/Header.vue')['default']
    HomeSectionHighlight: typeof import('./components/home/section/Highlight.vue')['default']
    Image: typeof import('primevue/image')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/SearchInput.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TokensHeader: typeof import('./components/tokens/Header.vue')['default']
    TokensHeaderBasicInfo: typeof import('./components/tokens/header/BasicInfo.vue')['default']
    TokensHeaderMore: typeof import('./components/tokens/header/More.vue')['default']
    TokensHeaderOverview: typeof import('./components/tokens/header/Overview.vue')['default']
    TokensSectionHeader: typeof import('./components/tokens/section/Header.vue')['default']
    TokensSectionHeaderBasicInfo: typeof import('./components/tokens/section/header/BasicInfo.vue')['default']
    TokensSectionHeaderMore: typeof import('./components/tokens/section/header/More.vue')['default']
    TokensSectionHeaderOverview: typeof import('./components/tokens/section/header/Overview.vue')['default']
    'TokensSectionHeaderOverview.1': typeof import('./components/tokens/section/header/Overview.1.vue')['default']
    TokensSectionTable: typeof import('./components/tokens/section/Table.vue')['default']
    TokensTable: typeof import('./components/tokens/Table.vue')['default']
    WalletHeader: typeof import('./components/wallet/Header.vue')['default']
    WalletTable: typeof import('./components/wallet/Table.vue')['default']
  }
}
