/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlockchainBlockHeader: typeof import('./components/blockchain/block/Header.vue')['default']
    BlockchainBlockTable: typeof import('./components/blockchain/block/Table.vue')['default']
    BlockchainBlockTrxHeader: typeof import('./components/blockchain/block/trx/Header.vue')['default']
    BlockchainBlockTrxOverview: typeof import('./components/blockchain/block/trx/Overview.vue')['default']
    BlockchainHeader: typeof import('./components/blockchain/Header.vue')['default']
    BlockchainTable: typeof import('./components/blockchain/Table.vue')['default']
    BlockchainVotes: typeof import('./components/blockchain/Votes.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    CoverWrapper: typeof import('./components/CoverWrapper.vue')['default']
    DappLoading: typeof import('./components/core/DappLoading.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataTableEmpty: typeof import('./components/core/DataTableEmpty.vue')['default']
    Discarded: typeof import('./components/core/Discarded.vue')['default']
    HomeCommunity: typeof import('./components/home/Community.vue')['default']
    HomeHeader: typeof import('./components/home/Header.vue')['default']
    HomeHighlight: typeof import('./components/home/Highlight.vue')['default']
    Image: typeof import('primevue/image')['default']
    Loading: typeof import('./components/core/Loading.vue')['default']
    NavBar: typeof import('./components/core/NavBar.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/SearchInput.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TokensHeader: typeof import('./components/tokens/Header.vue')['default']
    TokensHeaderBasicInfo: typeof import('./components/tokens/header/BasicInfo.vue')['default']
    TokensHeaderMore: typeof import('./components/tokens/header/More.vue')['default']
    TokensHeaderOverview: typeof import('./components/tokens/header/Overview.vue')['default']
    TokensTable: typeof import('./components/tokens/Table.vue')['default']
    WalletHeader: typeof import('./components/wallet/Header.vue')['default']
    WalletTable: typeof import('./components/wallet/Table.vue')['default']
  }
}
