/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/block/[height]/': RouteRecordInfo<'/block/[height]/', '/block/:height', { height: ParamValue<true> }, { height: ParamValue<false> }>,
    '/block/[height]/event-record/[hash]/': RouteRecordInfo<'/block/[height]/event-record/[hash]/', '/block/:height/event-record/:hash', { height: ParamValue<true>, hash: ParamValue<true> }, { height: ParamValue<false>, hash: ParamValue<false> }>,
    '/block/[height]/extrinsic/[extrinsicHash]/': RouteRecordInfo<'/block/[height]/extrinsic/[extrinsicHash]/', '/block/:height/extrinsic/:extrinsicHash', { height: ParamValue<true>, extrinsicHash: ParamValue<true> }, { height: ParamValue<false>, extrinsicHash: ParamValue<false> }>,
    '/block/[height]/trx/[hash]': RouteRecordInfo<'/block/[height]/trx/[hash]', '/block/:height/trx/:hash', { height: ParamValue<true>, hash: ParamValue<true> }, { height: ParamValue<false>, hash: ParamValue<false> }>,
    '/blockchain': RouteRecordInfo<'/blockchain', '/blockchain', Record<never, never>, Record<never, never>>,
    '/indexer/search/transfer/[extrinsicHash]': RouteRecordInfo<'/indexer/search/transfer/[extrinsicHash]', '/indexer/search/transfer/:extrinsicHash', { extrinsicHash: ParamValue<true> }, { extrinsicHash: ParamValue<false> }>,
    '/tokens': RouteRecordInfo<'/tokens', '/tokens', Record<never, never>, Record<never, never>>,
    '/wallet/[address]': RouteRecordInfo<'/wallet/[address]', '/wallet/:address', { address: ParamValue<true> }, { address: ParamValue<false> }>,
  }
}
